# Generated by Django 3.0.2 on 2020-02-01 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('nom_classe', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password_classe', models.CharField(max_length=50)),
                ('login_classe', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Classe',
                'ordering': ['nom_classe'],
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('nom_cours', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('duree', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_eleve', models.CharField(max_length=50)),
                ('prenom_eleve', models.CharField(max_length=50)),
                ('grade_eleve', models.CharField(max_length=40)),
                ('nom_classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Classe')),
            ],
            options={
                'verbose_name': 'Eleve',
                'ordering': ['nom_eleve'],
            },
        ),
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('nom_prof', models.CharField(max_length=50)),
                ('prenom_prof', models.CharField(max_length=50)),
                ('mail_prof', models.CharField(max_length=50)),
                ('login_prof', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password_prof', models.CharField(max_length=50)),
                ('grade_prof', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Secretaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PresAbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Eleve')),
                ('nom_cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Cours')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('contenu', models.TextField()),
                ('login_prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Prof')),
            ],
        ),
        migrations.CreateModel(
            name='Enseigner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Prof')),
                ('nom_classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Classe')),
            ],
        ),
        migrations.AddField(
            model_name='cours',
            name='login_prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Prof'),
        ),
        migrations.AddField(
            model_name='cours',
            name='nom_classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Classe'),
        ),
        migrations.CreateModel(
            name='CahierTexte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_cours', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('contenu', models.TextField()),
                ('id_eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Eleve')),
            ],
            options={
                'verbose_name': 'Cahier de texte',
                'ordering': ['date'],
            },
        ),
    ]
