# Generated by Django 2.2.7 on 2020-02-29 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prof',
            name='photo',
        ),
    ]
