# Generated by Django 2.2.7 on 2020-02-22 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsable_eleve',
            options={'ordering': ['prenom_eleve'], 'verbose_name_plural': 'Responsable de classe'},
        ),
        migrations.RemoveField(
            model_name='classe',
            name='login_classe',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='password_classe',
        ),
        migrations.RemoveField(
            model_name='prof',
            name='login_prof',
        ),
        migrations.RemoveField(
            model_name='prof',
            name='password_prof',
        ),
        migrations.RemoveField(
            model_name='responsable_eleve',
            name='login_res',
        ),
        migrations.RemoveField(
            model_name='responsable_eleve',
            name='pasword_res',
        ),
        migrations.RemoveField(
            model_name='secretaire',
            name='login',
        ),
        migrations.RemoveField(
            model_name='secretaire',
            name='password',
        ),
    ]
