# Generated by Django 2.2.7 on 2020-02-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200222_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='id_prof',
            new_name='id_prof_recep',
        ),
        migrations.AddField(
            model_name='notification',
            name='id_prof_emmet',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
