# Generated by Django 2.2.7 on 2020-02-29 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_prof_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cahiertexte',
            name='id_eleve',
        ),
        migrations.AddField(
            model_name='cahiertexte',
            name='id_classe',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='myapp.Classe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presabs',
            name='id_classe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Classe'),
            preserve_default=False,
        ),
    ]
