# Generated by Django 2.2.7 on 2020-02-05 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200204_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prof',
            name='grade_prof',
        ),
        migrations.RemoveField(
            model_name='responsable_eleve',
            name='id',
        ),
        migrations.RemoveField(
            model_name='responsable_eleve',
            name='nom_classe',
        ),
        migrations.RemoveField(
            model_name='responsable_eleve',
            name='nom_res',
        ),
        migrations.RemoveField(
            model_name='responsable_eleve',
            name='prenom_res',
        ),
        migrations.AddField(
            model_name='responsable_eleve',
            name='eleve_ptr',
            field=models.OneToOneField(auto_created=True, default=2, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.Eleve'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Responsable_Prof',
            fields=[
                ('prof_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.Prof')),
                ('id_classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Classe')),
            ],
            bases=('myapp.prof',),
        ),
    ]
