# Generated by Django 2.2.7 on 2020-02-23 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200223_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='id_prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Responsable_Prof'),
        ),
    ]
