# Generated by Django 2.2.7 on 2020-02-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200205_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='presabs',
            name='heure',
            field=models.CharField(default=3, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cahiertexte',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='presabs',
            name='date',
            field=models.DateField(),
        ),
    ]
