# Generated by Django 3.0.3 on 2020-02-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200223_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof',
            name='classe',
            field=models.ManyToManyField(to='myapp.Classe'),
        ),
    ]
