# Generated by Django 2.2.7 on 2020-03-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200301_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseigner',
            name='duree',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
