# Generated by Django 2.2.7 on 2020-03-01 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_enseigner_duree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseigner',
            name='duree',
        ),
    ]
