# Generated by Django 2.2.7 on 2020-02-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200208_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presabs',
            name='id_eleve',
            field=models.CharField(max_length=500),
        ),
    ]
