# Generated by Django 2.2.7 on 2020-02-09 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20200209_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presabs',
            name='id_eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Eleve'),
        ),
    ]
