# Generated by Django 2.2.7 on 2020-03-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_prof_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretaire',
            name='photo',
            field=models.ImageField(default=1, upload_to='Images/'),
            preserve_default=False,
        ),
    ]
