# Generated by Django 2.2.7 on 2020-03-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_secretaire_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='photo',
            field=models.ImageField(default=2, upload_to='Images/'),
            preserve_default=False,
        ),
    ]
